version = '2'

[run]
tests = true

[linters]
default = 'none'
enable = [
  'asciicheck',
  'dogsled',
  'err113',
  'errcheck',
  'errorlint',
  'exhaustive',
  'exhaustruct',
  'funlen',
  'gochecknoglobals',
  'goconst',
  'gocritic',
  'gocyclo',
  'gosec',
  'govet',
  'ineffassign',
  'lll',
  'misspell',
  'nakedret',
  'nolintlint',
  'prealloc',
  'revive',
  'staticcheck',
  'unconvert',
  'unparam',
  'unused',
  'wrapcheck'
]

[linters.settings]
[linters.settings.exhaustive]
default-signifies-exhaustive = true

[linters.settings.lll]
line-length = 120
tab-width = 4

[linters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[[linters.exclusions.rules]]
linters = [
  'gosec'
]
# G306 - "Expect WriteFile permissions to be 0600 or less".
text = 'G306'

[formatters]
enable = [
  'gofumpt',
  'goimports'
]

[formatters.settings]
[formatters.settings.gofumpt]
extra-rules = true

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
