---
name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * SUN"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.15.x', '1.16.x']
        include:
          - go-version: '1.16.x'
            build-coverage: true
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl
            https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi
      - name: Build
        run: go build -v ./...

      - name: Test with coverage
        run: ${{ format('go test -race -coverprofile=cover.{0}.gcov -covermode=atomic ./...', matrix.go-version) }}

      - name: Convert coverage output to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.5
        with:
          infile: ${{ format('cover.{0}.gcov', matrix.go-version) }}
          outfile: ${{ format('cover.{0}.lcov', matrix.go-version) }}
        if: matrix.build-coverage && success()

      - name: Upload coverage
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ format('cover.{0}.lcov', matrix.go-version) }}
        if: matrix.build-coverage && success()
